### ISSUE TITLE
Need more info!

### ISSUE THREAD

**Issue by mbac** [robertvoy/ComfyUI-Flux-Continuum#8]
Hi!

I really love your approach with this workflow, but I really can't grasp the procedure for, say, using canny or other controls for img2img. More specifically, I don't understand how to define the starting image: is it the latest image I generated, or the image I have in the Img Load tab?

At the end of the tutorial video you ask for feedback on the need for more videos… Well, here's feedback: yes, please! 🙃

**Comment by robertvoy** [comment]
Thanks! Yes, the tutorial is coming soon.

Quick info for now:
- Any img2img operation (detailer, img2img, inpainting, outpainting etc.), but also upscaler, canny, depth, they all use the Img Load tab as an input
- For operations requiring a mask, use the Img Mask tab
- The other image load tabs: IP1, IP2, IP3/Face are used for Redux (the new IP Adapter), with IP3/Face also used in Face Swap

Using Canny:
1. Load image you want to use as an input for canny into the Img Load tab.
2. Set the output to Output - canny preprocessor
3. Run the workflow to preview your canny preprocessor output
4. Adjust the canny parameters in the Canny tab (below the image load nodes)
5. Change output to Output - canny
6. Run the workflow

Using Depth: same as above but you can tweak the depth map using the CC tab.

A common workflow:
1. Generate images with txt2img, until you find something you like
3. Right-click the output in the main window named Img Preview and Copy (Clipspace)
4. Right-click the Img Load tab and Paste (Clipspace)
> Now the generation from txt2img is your starting image for img2img operations
5. Create a mask in the Img Mask tab to change something
6. Set the output to Output - inpanting, adjust the prompt if needed, increase the guidance and run
7. Right-click the output in Img Preview and Copy (Clipspace) and Paste (Clipspace) into Img Load tab
8. Repeat the process with any other operations you need
9. Set the output to Output - upscaler
10. Set the upscale model and resolution multiply in the bottom right corner
11. Run workflow
12. You can stop here or you can run it through the ultimate upscaler

This pretty much covers it all and there is some more info in the tutorial that you've seen. Let me know if you have any more questions. This is helpful as I'll know what to include in the tutorial.

**Comment by mbac** [comment]
Awesome, thank you so much for the help, and the workflow.
